/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package b.com.visao;

/**
 *
 * @author lorrany.magalhaes
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGq1 = new javax.swing.ButtonGroup();
        bGq2 = new javax.swing.ButtonGroup();
        bGq3 = new javax.swing.ButtonGroup();
        bGq4 = new javax.swing.ButtonGroup();
        bGq5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRvalor1 = new javax.swing.JRadioButton();
        jRvalor2 = new javax.swing.JRadioButton();
        jRvalor3 = new javax.swing.JRadioButton();
        jRvalor4 = new javax.swing.JRadioButton();
        jRvalor5 = new javax.swing.JRadioButton();
        jBselecionar = new javax.swing.JButton();
        jTquestao = new javax.swing.JTextField();
        jLresultado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTquestao2 = new javax.swing.JTextField();
        jRq2valor1 = new javax.swing.JRadioButton();
        jRq2valor2 = new javax.swing.JRadioButton();
        jRq2valor3 = new javax.swing.JRadioButton();
        jRq2valor4 = new javax.swing.JRadioButton();
        jRq2valor5 = new javax.swing.JRadioButton();
        jBselecionar2 = new javax.swing.JButton();
        jLresultado2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTquestao3 = new javax.swing.JTextField();
        jRq3valor1 = new javax.swing.JRadioButton();
        jRq3valor2 = new javax.swing.JRadioButton();
        jRq3valor3 = new javax.swing.JRadioButton();
        jRq3valor4 = new javax.swing.JRadioButton();
        jRq3valor5 = new javax.swing.JRadioButton();
        jBselecionar3 = new javax.swing.JButton();
        jLresultado3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTquestao5 = new javax.swing.JTextField();
        jRq5valor1 = new javax.swing.JRadioButton();
        jRq5valor2 = new javax.swing.JRadioButton();
        jRq5valor3 = new javax.swing.JRadioButton();
        jRq5valor4 = new javax.swing.JRadioButton();
        jRq5valor5 = new javax.swing.JRadioButton();
        jBselecionar5 = new javax.swing.JButton();
        jLresultado5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTquestao4 = new javax.swing.JTextField();
        jRq4valor1 = new javax.swing.JRadioButton();
        jRq4valor2 = new javax.swing.JRadioButton();
        jRq4valor3 = new javax.swing.JRadioButton();
        jRq4valor4 = new javax.swing.JRadioButton();
        jRq4valor5 = new javax.swing.JRadioButton();
        jBselecionar4 = new javax.swing.JButton();
        jLresultado4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        bGq1.add(jRvalor1);
        jRvalor1.setText("a)  Classe");

        bGq1.add(jRvalor2);
        jRvalor2.setText("b) Objeto");

        bGq1.add(jRvalor3);
        jRvalor3.setText("c) Instância");

        bGq1.add(jRvalor4);
        jRvalor4.setText("d) Método");

        bGq1.add(jRvalor5);
        jRvalor5.setText("e) Pacote");

        jBselecionar.setText("selecionar");
        jBselecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBselecionarActionPerformed(evt);
            }
        });

        jTquestao.setText("Questão 1: O que é uma classe em Java?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLresultado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jRvalor1)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTquestao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRvalor2)
                                .addGap(18, 18, 18)
                                .addComponent(jRvalor3)
                                .addGap(18, 18, 18)
                                .addComponent(jRvalor4)
                                .addGap(18, 18, 18)
                                .addComponent(jRvalor5))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jBselecionar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTquestao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRvalor3)
                    .addComponent(jRvalor4)
                    .addComponent(jRvalor5)
                    .addComponent(jRvalor2)
                    .addComponent(jRvalor1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBselecionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLresultado)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));

        jTquestao2.setText("Questão 2: Qual é a principal característica do encapsulamento?");

        bGq2.add(jRq2valor1);
        jRq2valor1.setText("a) Acesso restrito");

        bGq2.add(jRq2valor2);
        jRq2valor2.setText("b) Herança");

        bGq2.add(jRq2valor3);
        jRq2valor3.setText("c) Polimorfismo");

        bGq2.add(jRq2valor4);
        jRq2valor4.setText("d) Abstração");

        bGq2.add(jRq2valor5);
        jRq2valor5.setText("e) Interface");

        jBselecionar2.setText("selecionar");
        jBselecionar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBselecionar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRq2valor1)
                        .addGap(18, 18, 18)
                        .addComponent(jRq2valor2)
                        .addGap(18, 18, 18)
                        .addComponent(jRq2valor3)
                        .addGap(18, 18, 18)
                        .addComponent(jRq2valor4)
                        .addGap(18, 18, 18)
                        .addComponent(jRq2valor5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jBselecionar2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jLresultado2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jTquestao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTquestao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRq2valor1)
                    .addComponent(jRq2valor2)
                    .addComponent(jRq2valor3)
                    .addComponent(jRq2valor4)
                    .addComponent(jRq2valor5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBselecionar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLresultado2)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jTquestao3.setText("Questão 3: O que permite que uma classe herde atributos de outra?");

        bGq3.add(jRq3valor1);
        jRq3valor1.setText("a) Classe abstrata");

        bGq3.add(jRq3valor2);
        jRq3valor2.setText("b) Interface");

        bGq3.add(jRq3valor3);
        jRq3valor3.setText("c) Herança");

        bGq3.add(jRq3valor4);
        jRq3valor4.setText("d) Polimorfismo");

        bGq3.add(jRq3valor5);
        jRq3valor5.setText("e) Método");

        jBselecionar3.setText("selecionar");
        jBselecionar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBselecionar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLresultado3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jRq3valor1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTquestao3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jRq3valor2)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jBselecionar3))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jRq3valor3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRq3valor4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRq3valor5)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jTquestao3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRq3valor1)
                    .addComponent(jRq3valor2)
                    .addComponent(jRq3valor3)
                    .addComponent(jRq3valor4)
                    .addComponent(jRq3valor5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBselecionar3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLresultado3)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        jTquestao5.setText("Questão 5: O que é um objeto?");

        bGq5.add(jRq5valor1);
        jRq5valor1.setText("a) Uma instância de uma classe");

        bGq5.add(jRq5valor2);
        jRq5valor2.setText("b) Uma variável primitiva");

        bGq5.add(jRq5valor3);
        jRq5valor3.setText("c) Um tipo de dado");

        bGq5.add(jRq5valor4);
        jRq5valor4.setText("d) Um método estático");

        bGq5.add(jRq5valor5);
        jRq5valor5.setText("e) Uma interface");
        jRq5valor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRq5valor5ActionPerformed(evt);
            }
        });

        jBselecionar5.setText("selecionar");
        jBselecionar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBselecionar5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRq5valor1)
                                    .addComponent(jRq5valor2)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(219, 219, 219)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTquestao5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRq5valor3)
                                            .addComponent(jRq5valor4))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRq5valor5))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLresultado5))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jBselecionar5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTquestao5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRq5valor1)
                    .addComponent(jRq5valor3)
                    .addComponent(jRq5valor5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRq5valor2)
                    .addComponent(jRq5valor4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBselecionar5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLresultado5)
                .addGap(14, 14, 14))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));

        jTquestao4.setText("Questão 4: O que é polimorfismo?");

        bGq4.add(jRq4valor1);
        jRq4valor1.setText("a) Uma classe que não pode ser instanciada");

        bGq4.add(jRq4valor2);
        jRq4valor2.setText("b) Métodos com o mesmo nome, mas comportamentos diferentes");

        bGq4.add(jRq4valor3);
        jRq4valor3.setText("c) Um tipo de variável");

        bGq4.add(jRq4valor4);
        jRq4valor4.setText("d) Um pacote de classes");

        bGq4.add(jRq4valor5);
        jRq4valor5.setText("e) Um método que não retorna valor");

        jBselecionar4.setText("selecionar");
        jBselecionar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBselecionar4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRq4valor1)
                    .addComponent(jRq4valor2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBselecionar4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRq4valor3)
                                .addGap(54, 54, 54)
                                .addComponent(jRq4valor5))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRq4valor4)
                                .addGap(196, 196, 196)
                                .addComponent(jLresultado4)))))
                .addGap(153, 153, 153))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jTquestao4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTquestao4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRq4valor1)
                    .addComponent(jRq4valor3)
                    .addComponent(jRq4valor5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRq4valor2)
                    .addComponent(jRq4valor4)
                    .addComponent(jLresultado4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBselecionar4)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBselecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBselecionarActionPerformed
        // TODO add your handling code here:
        if(jRq1a.isSelected()){
       jLresultado.setText("Errou vai estudar");
      }
      else if(jRq1b.isSelected()){
       jLresultado.setText("Errou vai estudar");
      
      }
      else if(jRq1correta.isSelected()){
       total.setOpcao(1);
       jLresultado.setText("Acertou"+total.somar());
      }
      else if(jRq1d.isSelected()){
       jLresultado.setText("Errou vai estudar");
      }
     else if(jRq1e.isSelected()){
       jLresultado.setText("Errou vai estudar");
       
      }
     else{
     jLresultado.setText("Opção Invalida");
     }
      jLtotal.setText("Total de acertos "+total.somar());
      jBq1.setEnabled(false);
    } 
    }//GEN-LAST:event_jBselecionarActionPerformed

    private void jRq5valor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRq5valor5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRq5valor5ActionPerformed

    private void jBselecionar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBselecionar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBselecionar2ActionPerformed

    private void jBselecionar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBselecionar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBselecionar3ActionPerformed

    private void jBselecionar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBselecionar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBselecionar4ActionPerformed

    private void jBselecionar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBselecionar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBselecionar5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGq1;
    private javax.swing.ButtonGroup bGq2;
    private javax.swing.ButtonGroup bGq3;
    private javax.swing.ButtonGroup bGq4;
    private javax.swing.ButtonGroup bGq5;
    private javax.swing.JButton jBselecionar;
    private javax.swing.JButton jBselecionar2;
    private javax.swing.JButton jBselecionar3;
    private javax.swing.JButton jBselecionar4;
    private javax.swing.JButton jBselecionar5;
    private javax.swing.JLabel jLresultado;
    private javax.swing.JLabel jLresultado2;
    private javax.swing.JLabel jLresultado3;
    private javax.swing.JLabel jLresultado4;
    private javax.swing.JLabel jLresultado5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRq2valor1;
    private javax.swing.JRadioButton jRq2valor2;
    private javax.swing.JRadioButton jRq2valor3;
    private javax.swing.JRadioButton jRq2valor4;
    private javax.swing.JRadioButton jRq2valor5;
    private javax.swing.JRadioButton jRq3valor1;
    private javax.swing.JRadioButton jRq3valor2;
    private javax.swing.JRadioButton jRq3valor3;
    private javax.swing.JRadioButton jRq3valor4;
    private javax.swing.JRadioButton jRq3valor5;
    private javax.swing.JRadioButton jRq4valor1;
    private javax.swing.JRadioButton jRq4valor2;
    private javax.swing.JRadioButton jRq4valor3;
    private javax.swing.JRadioButton jRq4valor4;
    private javax.swing.JRadioButton jRq4valor5;
    private javax.swing.JRadioButton jRq5valor1;
    private javax.swing.JRadioButton jRq5valor2;
    private javax.swing.JRadioButton jRq5valor3;
    private javax.swing.JRadioButton jRq5valor4;
    private javax.swing.JRadioButton jRq5valor5;
    private javax.swing.JRadioButton jRvalor1;
    private javax.swing.JRadioButton jRvalor2;
    private javax.swing.JRadioButton jRvalor3;
    private javax.swing.JRadioButton jRvalor4;
    private javax.swing.JRadioButton jRvalor5;
    private javax.swing.JTextField jTquestao;
    private javax.swing.JTextField jTquestao2;
    private javax.swing.JTextField jTquestao3;
    private javax.swing.JTextField jTquestao4;
    private javax.swing.JTextField jTquestao5;
    // End of variables declaration//GEN-END:variables
}
